### ISSUE TITLE
More graceful disconnect/reconnect logic

### ISSUE THREAD

**Issue by mattdsteele** [muesli/prism#1]
I think you're tracking on this, but I'm encountering broken pipes when there's a disconnect from the downstream RTMP streams (for example, if an Owncast instance restarts).

It manifests itself with a wall of errors like:

```
write tcp 206.189.205.219:50394->172.104.12.173:1935: write: broken pipe
```

My current workaround is just to kill the prism instance.

**Comment by muesli** [comment]
You're right, that's a problematic situation at the moment. I do have it marked as a `TODO` in the sources, as I'm not quite sure yet how I want to handle this situation:

1. Abort with an error
2. Re-connect and drop frames intermittently
3. Re-connect and buffer missed frames, which would then be re-played as soon as the connection was re-established

Feedback appreciated!

**Comment by muesli** [comment]
I've opted for the second option: we try to re-establish a connection, but won't buffer any packages to keep the multiple outgoing streams in sync.

Fixed in master.
